# Rebuilds the vocabulary from db/seeds/vocabulary.yml.
# The YAML is the source of truth: each run wipes terms/translations and reloads,
# so editing the YAML and re-running `bin/rails db:seed` always converges.
require "yaml"

path = Rails.root.join("db/seeds/vocabulary.yml")

unless File.exist?(path)
  warn "No db/seeds/vocabulary.yml yet — skipping vocabulary seed."
  return
end

entries = YAML.load_file(path)

# The "Basics" category (pronouns, verbs, numbers, … — generated by `rake basics:generate`)
# rides in the same loop. Its verb cards carry type: "verb" -> kind: "phrase".
basics_path = Rails.root.join("db/seeds/basics.yml")
entries += YAML.load_file(basics_path) if File.exist?(basics_path)

langs = Translation::LANGUAGES.keys

ActiveRecord::Base.transaction do
  Attempt.delete_all # term ids are rebuilt below; reseeding therefore resets miss history
  Translation.delete_all
  Term.delete_all
  Deck.delete_all

  # The seeded Dutch vocabulary belongs to Mihai (the first user).
  owner = User.find_or_create_by!(email_address: "mihai@example.com") do |u|
    u.name = "Mihai"
    u.password = "password" # dev seed only
    u.target_language = "nl"
    u.source_language = "en"
  end

  deck_cache = {}
  positions = Hash.new(0)

  entries.each do |row|
    deck_name = row.fetch("deck")
    deck = deck_cache[deck_name] ||= Deck.create!(name: deck_name, position: deck_cache.size, user: owner)

    kind = row["type"] == "verb" ? "phrase" : "word"
    term = deck.terms.create!(kind: kind, key: row["key"].presence, position: (positions[deck.id] += 1))

    langs.each do |lang|
      value = row[lang]
      next if value.nil?

      if value.is_a?(Hash)
        term.translations.create!(
          language: lang,
          text: value["text"],
          article: value["article"],
          alternates: Array(value["alt"]).join("|").presence
        )
      else
        term.translations.create!(language: lang, text: value.to_s)
      end
    end
  end

  # English answer alternates (big -> large, no entry -> wrong way, ...).
  alt_path = Rails.root.join("db/seeds/alternates.yml")
  if File.exist?(alt_path)
    YAML.load_file(alt_path).each do |label, alts|
      next if alts.blank?
      Translation.where(language: "en", text: label).update_all(alternates: Array(alts).join("|"))
    end
  end

  # Sentences -> their own "Sentences" deck, kind: "sentence".
  sent_path = Rails.root.join("db/seeds/sentences.yml")
  if File.exist?(sent_path)
    sdeck = Deck.create!(name: "Sentences", position: deck_cache.size + 1, user: owner)
    YAML.load_file(sent_path).each_with_index do |row, i|
      term = sdeck.terms.create!(kind: "sentence", position: i + 1)
      Translation::LANGUAGES.keys.each do |lang|
        text = row[lang]
        next if text.blank?
        term.translations.create!(language: lang, text: text)
      end
    end
  end
end

puts "Seeded #{Deck.count} decks, #{Term.count} terms, #{Translation.count} translations."
